---
title: "Week 8 Lab Session"
author: 'Nicole (PID: A18116280)'
date: "2025-11-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1. Proportopm pg G/G in a population

Downloaded a CSV file from Ensemble < 

Here we read this CSV file

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378 (1).csv")
head(mxl)
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
table(mxl$Genotype..forward.strand.) /nrow(mxl) * 100
```

## Section 4: Population Scale Analysis

One sample is obviously not enough to know what is happening in a population. You are
interested in assessing genetic differences on a population scale. 

How many samples do we have?

```{r}
expr <- read.table("rs8067378_ENSG00000172057.6.txt")
head(expr)
```

```{r}
nrow(expr)
```

```{r}
table(expr$geno)
```

```{r}
library(ggplot2)
```

Let's make a boxplot

```{r}
ggplot(expr) + aes(geno, exp, fill=geno) +
  geom_boxplot(notch=TRUE)
```

